// <auto-generated />
using System;
using Data.Persistence.Classes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Data.Persistence.Migrations
{
    [DbContext(typeof(AddContext))]
    [Migration("20190805073613_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Contracts.Contract", b =>
                {
                    b.Property<long>("ContractId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ConsumerId");

                    b.Property<long>("ContractorId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Number");

                    b.Property<decimal?>("Price");

                    b.HasKey("ContractId");

                    b.ToTable("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
